name: Upload Assets Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Folder
        run: |
          7z a -tzip -mx=9 Assets.zip . \
          -x!.git \
          -x!.github \
          -x!README.md \
          -x!readme.md \
          -x!LICENSE \
          -x!.gitignore

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: Assets.zip
          tag_name: latest
          name: Latest Assets
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
